orbs:
  node: circleci/node@4.2.1

version: 2.1

workflows:
  test-deploy:
    jobs:
      - test
  app-tests:
    jobs:
      - build

jobs:
  test:
    docker:
      - image: cimg/node:16.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      -run:
          name: Reticulating splines
          command: node --version
      - run:
          name: Run Tests
          command: npm run test 
  build:
      docker:
        - image: docker
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: docker image ls
        - run: docker volume ls
        - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
        - run: docker volume ls

